import test from 'node:test';
import assert from 'node:assert/strict';
import {newWorkspace,prepareChange,applyChange,contentHash} from '../state/builderChangeTransaction.mjs';
import {createDurableLandingWorkspace,createLocalWorkspaceStore} from '../state/authorizedRegressionFixture.mjs';
import {functionalValidation,inspectStaticDocument} from './functionalLandingValidation.mjs';
import {renderLandingArtifact} from './landingArtifact.mjs';
const base={projectId:'s7',projectKind:'landing',primaryCTA:'Consultar',visualAccent:'amber',ctas:[{id:'hero-primary-cta',intent:'primary',label:'Consultar',href:'#tail'}],blocks:[{id:'hero',type:'hero',order:0,props:{title:'Inicio'}},{id:'info',type:'trust',canonicalStatic:1,order:1,props:{title:'Info',items:['Seguro']}},{id:'tail',type:'trust',canonicalStatic:1,order:2,props:{title:'Destino',items:['Final']}}]};
const edit={type:'update_static_section',id:'info',sectionType:'trust',content:{title:'Nuevo',description:'Texto',items:['Uno']}};
const move={type:'move_static_section',id:'info',afterId:'tail'};
function fixture(){const data=new Map();let queue=Promise.resolve();const storage={getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v)};const store=createLocalWorkspaceStore(storage,{request:(k,o,fn)=>{const p=queue.then(fn);queue=p.catch(()=>{});return p;}});return {data,open:(owner='alice')=>createDurableLandingWorkspace(store,owner,'s7')};}
test('PASS final composite, identity, single apply, reload, exact artifact revert',async()=>{const f=fixture(),r=f.open();const before=await r.initialize(base);const p=await r.propose([edit,move]);assert.equal(p.review.functionalValidation.status,'PASS');assert.deepEqual(p.review.functionalValidation,p.proposal.functionalValidation);const after=await r.apply(p);assert.equal(after.workspace.revision,1);assert.deepEqual(after.artifact,p.proposal.artifact);assert.deepEqual(await f.open().read(),after);const back=await r.revert(1);assert.deepEqual(back.workspace.committed,base);assert.deepEqual(back.artifact,before.artifact);});
test('removed final target fails review and both core/durable apply without mutation',async()=>{const f=fixture(),r=f.open();const before=await r.initialize(base);const p=await r.propose([edit,{type:'remove_static_section',id:'tail'}]);assert.equal(p.review.validation,'FAIL');assert.ok(p.review.functionalValidation.failedInvariants.includes('NAVIGATION'));await assert.rejects(r.apply(p),/FUNCTIONAL_VALIDATION_FAIL/);await assert.rejects(applyChange(before.workspace,p.proposal),/FUNCTIONAL_VALIDATION_FAIL/);assert.deepEqual(await r.read(),before);});
test('missing target, duplicate identity, unsafe link are functional failures',async()=>{for(const state of [{...base,ctas:[{intent:'primary',href:'#missing'}]},{...base,blocks:base.blocks.map(b=>({...b,id:'duplicate'}))},{...base,ctas:[{intent:'primary',href:'javascript:alert(1)'}]}]){const ws=newWorkspace(state),p=await prepareChange(ws,[{type:'set_accent',value:'orange'}]);assert.equal(p.functionalValidation.status,'FAIL');await assert.rejects(applyChange(ws,p),/FUNCTIONAL_VALIDATION_FAIL/);}});
test('PASS cannot be replayed after tampering or omission, stale revision, owner change, concurrent winner',async()=>{const f=fixture(),r=f.open();const before=await r.initialize(base);const p=await r.propose([edit,move]);for(const mutate of [q=>q.proposal.artifact.html+='x',q=>q.proposal.candidate.primaryCTA='x',q=>q.proposal.operations.reverse(),q=>q.proposal.functionalValidation.status='FAIL',q=>delete q.proposal.functionalValidation,q=>q.proposal.ownerId='bob',q=>q.proposal.baseRevision++,q=>q.review.functionalValidation.checks=[]]){const q=structuredClone(p);mutate(q);await assert.rejects(async()=>r.apply(q));assert.deepEqual(await r.read(),before);}const results=await Promise.allSettled([r.apply(p),f.open().apply(p)]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert.match(results.find(x=>x.status==='rejected').reason.message,/STALE_(WRITE|DECISION)/);});
test('hostile content stays text; unsupported markup and internal validator failure fail closed',async()=>{const ws=newWorkspace(base);const p=await prepareChange(ws,[{...edit,content:{title:'<script>alert(1)</script>',description:'<img src=x onerror=alert(1)>',items:['<a href="javascript:x">x</a>']}}]);assert.equal(p.functionalValidation.status,'PASS');assert.ok(!p.artifact.html.includes('<script>'));assert.throws(()=>inspectStaticDocument(p.artifact.html.replace('</main>','<script>x</script></main>')),/ACTIVE_OR_UNSUPPORTED/);const q=structuredClone(p);q.artifact.html=null;assert.equal((await functionalValidation(q)).status,'BLOCKED');q.functionalValidation=await functionalValidation(q);await assert.rejects(applyChange(ws,q));});
test('legacy persisted v1 artifact recovers and revert restores exact bytes',async()=>{const f=fixture(),r=f.open();const record=await r.initialize(base);record.artifact=renderLandingArtifact(base,true);const {digest,...body}=record;record.digest=await contentHash(body);f.data.set(r.key,JSON.stringify(record));assert.deepEqual((await r.read()).artifact,record.artifact);const p=await r.propose([edit]);await r.apply(p);assert.deepEqual((await r.revert(1)).artifact,record.artifact);});
