import React from 'react';
import { createRoot } from 'react-dom/client';
import { act } from 'react-dom/test-utils';
import BuilderWorkspacePage from './BuilderWorkspacePage';
import { api } from '../../../lib/apiClient';
let mockUser, mockProps;
const mockLocation = { search: '?project_id=p', state: { initialPrompt: 'unowned navigation text' } };
const mockNavigate = jest.fn();
jest.mock('react-router-dom', () => ({ useLocation: () => mockLocation, useNavigate: () => mockNavigate }));
jest.mock('../../../context/AuthContext', () => ({ useAuth: () => ({ user: mockUser }) }));
jest.mock('../../../lib/apiClient', () => ({ api: { get: jest.fn() } }));
jest.mock('../../../lib/economicRequest', () => ({ economicPost: jest.fn() }));
jest.mock('sonner', () => ({ toast: { error: jest.fn() } }));
jest.mock('../../app-shell/layout/AppShellLayout', () => ({ __esModule: true, default: ({ children }) => children }));
jest.mock('./BuilderWorkspaceLayout', () => ({ __esModule: true, default: (props) => { mockProps = props; return <div>{props.ownerId}:{props.project?.input_content}</div>; } }));
globalThis.IS_REACT_ACT_ENVIRONMENT = true;
test('session user_id binds owner; account switch refetches and rejects late previous response', async () => {
  const node = document.createElement('div'); const root = createRoot(node);
  let resolveAlice;
  api.get.mockImplementationOnce(() => new Promise((resolve) => { resolveAlice = resolve; }))
    .mockResolvedValueOnce({ data: { project_id: 'p', input_content: 'Bob project' } });
  mockUser = { user_id: 'alice' };
  await act(async () => { root.render(<BuilderWorkspacePage />); });
  expect(mockProps.ownerId).toBe('alice'); expect(mockProps.project).toBeNull();
  mockUser = { user_id: 'bob' };
  await act(async () => { root.render(<BuilderWorkspacePage />); });
  expect(api.get).toHaveBeenCalledTimes(2);
  expect(mockProps.ownerId).toBe('bob'); expect(mockProps.initialPrompt).toBe('Bob project');
  await act(async () => { resolveAlice({ data: { project_id: 'p', input_content: 'Alice private' } }); });
  expect(node.textContent).not.toContain('Alice private'); expect(mockProps.project.input_content).toBe('Bob project');
  mockUser = false; await act(async () => { root.render(<BuilderWorkspacePage />); });
  expect(node.textContent).toContain('sesión autenticada'); expect(node.textContent).not.toContain('Bob project');
  act(() => root.unmount());
});
