import test from 'node:test';
import assert from 'node:assert/strict';
import {createDurableLandingWorkspace,createLocalWorkspaceStore} from './authorizedRegressionFixture.mjs';
import {classifyRepair,prepareRepair} from './boundedLandingRepair.mjs';
import {newWorkspace,prepareChange,applyChange} from './builderChangeTransaction.mjs';
const base={projectId:'repair',projectKind:'landing',primaryCTA:'Ver destino',visualAccent:'amber',ctas:[{intent:'primary',href:'#target',label:'Ver destino'}],blocks:[{id:'hero',type:'hero',order:0,props:{title:'Inicio'}},{id:'info',type:'trust',canonicalStatic:1,order:1,props:{title:'Info',items:['Contenido']}},{id:'target',type:'trust',canonicalStatic:1,order:2,props:{title:'Destino',items:['Final']}}]};
const operations=[{type:'update_static_section',id:'info',sectionType:'trust',content:{title:'Editado',description:'Local',items:['Texto']}},{type:'remove_static_section',id:'target'}];
function fixture(){const data=new Map();let queue=Promise.resolve();let quota=false;const store=createLocalWorkspaceStore({getItem:k=>data.get(k)??null,setItem:(k,v)=>{if(quota)throw new Error('QUOTA');data.set(k,v);}},{request:(k,o,fn)=>{const p=queue.then(fn);queue=p.catch(()=>{});return p;}});return {data,setQuota:v=>quota=v,open:(owner='alice')=>createDurableLandingWorkspace(store,owner,'repair')};}
test('failure → minimal repair → fresh PASS → human apply → reload → exact revert',async()=>{const f=fixture(),r=f.open();const before=await r.initialize(base);const parent=await r.propose(operations);assert.equal(parent.review.validation,'FAIL');const saved=structuredClone(parent);await assert.rejects(r.apply(parent),/FUNCTIONAL_VALIDATION_FAIL/);const fixed=await r.repair(parent,'info');assert.deepEqual(parent,saved);assert.notEqual(fixed.proposal.operationId,parent.proposal.operationId);assert.equal(fixed.review.repair.status,'READY_FOR_HUMAN_REVIEW');assert.equal(fixed.review.validation,'PASS');assert.equal(fixed.proposal.repair.parentProposalId,parent.proposal.operationId);const minimal=structuredClone(parent.proposal.candidate);minimal.ctas[0].href='#info';minimal.destinationIntent=fixed.proposal.candidate.destinationIntent;assert.deepEqual(fixed.proposal.candidate,minimal);assert.equal(fixed.proposal.candidate.destinationIntent.sectionId,'info');assert.deepEqual(await r.read(),before);const after=await r.apply(await r.decide(fixed,'ACCEPT_WARNING','La sección cubre el destino.'));assert.equal(after.workspace.revision,1);assert.deepEqual(after.artifact,fixed.proposal.artifact);assert.deepEqual(await f.open().read(),after);const back=await r.revert(1);assert.deepEqual(back.workspace.committed,base);assert.deepEqual(back.artifact,before.artifact);});
test('lineage, failures, repair operations, hashes, old PASS and scope tampering never write',async()=>{const f=fixture(),r=f.open();const before=await r.initialize(base);const parent=await r.propose(operations),fixed=await r.repair(parent,'info');for(const mutate of [q=>q.proposal.repair.parentProposalId='other',q=>q.proposal.repair.failureHash='x',q=>q.proposal.repair.originalFailure.status='PASS',q=>q.proposal.repair.operations[0].to='#missing',q=>q.proposal.repair.operations.push({type:'set_accent',value:'orange'}),q=>q.proposal.candidateHash='x',q=>q.proposal.artifact.html+='x',q=>q.proposal.functionalValidation=parent.proposal.functionalValidation,q=>q.proposal.repair.parent.candidate.primaryCTA='x',q=>q.proposal.ownerId='bob',q=>q.proposal.baseRevision++,q=>delete q.proposal.repair,q=>q.proposal.candidate.visualAccent='orange']){const q=structuredClone(fixed);mutate(q);await assert.rejects(async()=>r.apply(q));assert.deepEqual(await r.read(),before);}const accepted=await r.decide(fixed,'ACCEPT_WARNING','La sección cubre el destino.');const auditBefore=await r.read();f.setQuota(true);await assert.rejects(r.apply(accepted),/QUOTA/);f.setQuota(false);assert.deepEqual(await r.read(),auditBefore);});
test('single attempt per parent and no recursive/cyclic repair',async()=>{const f=fixture(),r=f.open();await r.initialize(base);const parent=await r.propose(operations),fixed=await r.repair(parent,'info');await assert.rejects(r.repair(parent,'info'),/BUDGET/);assert.equal(classifyRepair(fixed.proposal).status,'BLOCKED');await assert.rejects(r.repair(fixed,'info'),/BUDGET/);const results=await Promise.allSettled([r.apply(await r.decide(fixed,'ACCEPT_WARNING','La sección cubre el destino.')),f.open().apply(fixed)]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert.match(results.find(x=>x.status==='rejected').reason.message,/STALE_/);await assert.rejects(f.open().repair(parent,'info'),/STALE/);});
test('unsafe protocol, duplicate identity and validator failure do not invent a repair',async()=>{for(const candidate of [{...base,ctas:[{intent:'primary',href:'javascript:x'}]},{...base,blocks:base.blocks.map(b=>({...b,id:'duplicate'}))}]){const ws=newWorkspace(candidate),p=await prepareChange(ws,[{type:'set_accent',value:'orange'}]);assert.equal(classifyRepair(p).status,'NOT_REPAIRABLE');await assert.rejects(prepareRepair(ws,p),/NO_SAFE/);}assert.equal(classifyRepair({functionalValidation:{status:'BLOCKED'}}).status,'BLOCKED');const ws=newWorkspace(base),p=await prepareChange(ws,operations);p.functionalValidation.checks=[];await assert.rejects(prepareRepair(ws,p),/IDENTITY/);await assert.rejects(applyChange(ws,p));});
