import {testDecision} from './semanticDecisionTestSupport.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import { availableDestinations, selectDestination } from './ctaDestinationIntent.mjs';
import { newWorkspace, prepareChange, applyReviewedChange as applyChange, revertChange } from './builderChangeTransaction.mjs';
import { createDurableLandingWorkspace, createLocalWorkspaceStore } from './authorizedRegressionFixture.mjs';
const base={projectId:'s9',projectKind:'landing',primaryCTA:'Consultar',ctas:[{id:'hero-primary-cta',intent:'primary',href:'#target'}],visualAccent:'amber',blocks:[{id:'hero',type:'hero',order:0,props:{title:'Inicio'}},{id:'info',type:'trust',canonicalStatic:1,order:1,props:{title:'Beneficios',items:['Uno']}},{id:'target',type:'trust',canonicalStatic:1,order:2,props:{title:'Final',items:['Dos']}}]};
function fixture(){let q=Promise.resolve();const data=new Map();const store=createLocalWorkspaceStore({getItem:k=>data.get(k)??null,setItem:(k,v)=>data.set(k,v)},{request:(k,o,fn)=>{const p=q.then(fn);q=p.catch(()=>{});return p;}});return {open:()=>createDurableLandingWorkspace(store,'alice','s9')};}
test('targets are real stable sections; explicit proposal has source/CTA/target identity; exact revert',async()=>{assert.deepEqual(availableDestinations(base).map(t=>t.sectionId),['hero','info','target']);assert.equal(availableDestinations({...base,blocks:[base.blocks[0],base.blocks[0]]}).length,0);assert.deepEqual(availableDestinations({...base,blocks:[{type:'hero'}]}),[]);assert.throws(()=>selectDestination(base,'missing'),/NOT_AVAILABLE/);const ws=newWorkspace(base),p=await prepareChange(ws,[{type:'set_primary_destination',value:'info'}]);assert.equal(p.functionalValidation.status,'PASS');assert.equal(p.candidate.destinationIntent.sourceSectionId,'hero');assert.equal(p.candidate.destinationIntent.targetFragment,'#info');assert.equal(ws.committed.ctas[0].href,'#target');const after=await applyChange(ws,p,await testDecision(ws,p));assert.equal(after.committed.ctas[0].href,'#info');assert.deepEqual((await revertChange(after,1)).committed,base);});
test('composite failure requires selection from FINAL candidate and preserves original intent',async()=>{const r=fixture().open();const initial=selectDestination(base,'target');const before=await r.initialize(initial);const parent=await r.propose([{type:'update_static_section',id:'info',sectionType:'trust',content:{title:'Nuevo destino',description:'',items:['Listo']}},{type:'remove_static_section',id:'target'}]);assert.equal(parent.review.validation,'FAIL');assert.equal(parent.review.repairability.status,'REPAIRABLE');assert.deepEqual(parent.review.repairability.targets.map(t=>t.sectionId),['hero','info']);await assert.rejects(r.repair(parent),/REQUIRES_DESTINATION_SELECTION/);const fixed=await r.repair(parent,'info');assert.equal(fixed.review.validation,'PASS');assert.equal(fixed.proposal.repair.originalDestinationIntent.sectionId,'target');assert.equal(fixed.proposal.repair.selection.label,'Nuevo destino');assert.deepEqual(await r.read(),before);await r.apply(await r.decide(fixed,'ACCEPT_WARNING','Destino elegido conscientemente.'));assert.equal((await r.read()).workspace.committed.destinationIntent.sectionId,'info');});
test('section movement never rebinds selected identity by position',async()=>{const ws=newWorkspace(selectDestination(base,'info'));const p=await prepareChange(ws,[{type:'move_static_section',id:'info',afterId:'target'}]);assert.equal(p.functionalValidation.status,'PASS');assert.equal(p.candidate.blocks.at(-1).id,'info');assert.equal(p.candidate.destinationIntent.targetFragment,'#info');assert.ok(p.artifact.html.includes('id="info"'));await applyChange(ws,p,await testDecision(ws,p));});
test('reviewed selection cannot be changed by label, fragment, source, candidate, artifact or lineage',async()=>{const r=fixture().open();const before=await r.initialize(base);const parent=await r.propose([{type:'remove_static_section',id:'target'}]);const fixed=await r.repair(parent,'info');for(const mutate of [p=>p.proposal.repair.selection.targetFragment='#hero',p=>p.proposal.repair.selection.sectionId='hero',p=>p.proposal.repair.selection.label='Beneficios falsos',p=>p.proposal.candidate.destinationIntent.ctaId='other',p=>p.proposal.candidate.destinationIntent.sourceSectionId='other',p=>p.proposal.candidate.destinationIntent.targetFragment='#hero',p=>p.proposal.repair.parentProposalId='wrong',p=>p.proposal.artifact.html=p.proposal.artifact.html.replace('href="#info"','href="#hero"'),p=>p.proposal.candidate.blocks.splice(1,1),p=>p.proposal.baseRevision++,p=>p.ownerId='bob']){const p=structuredClone(fixed);mutate(p);await assert.rejects(async()=>r.apply(p));assert.deepEqual(await r.read(),before);}});
test('two clients select different targets: only one reviewed target commits; old selection and repair stale',async()=>{const f=fixture(),a=f.open(),b=f.open();await a.initialize(base);const parent=await a.propose([{type:'remove_static_section',id:'target'}]);const one=await a.repair(parent,'info'),two=await b.repair(parent,'hero');const results=await Promise.allSettled([a.apply(await a.decide(one,'ACCEPT_WARNING','Destino elegido conscientemente.')),b.apply(two)]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert.match(results.find(x=>x.status==='rejected').reason.message,/STALE_/);await assert.rejects(f.open().repair(parent,'info'),/STALE/);});
